AWSTemplateFormatVersion: "2010-09-09"
Description: This template create a nat gateway in a public subnet

Parameters:
  ExportVpcStackName:
    Description: The name of the vpc stack that exports values
    Type: String

Resources:
  # NatGatewayEIP:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: VPC
  #     Tags:
  #       - Key: Name
  #         Value: EIP

  NatGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: eipalloc-0883634331a101466 #!GetAtt NatGatewayEIP.AllocationId
      SubnetId: 
        Fn::ImportValue: !Sub ${ExportVpcStackName}-PublicSubnet
      Tags:
        - Key: Name
          Value: Nat Gateway Public Subnet

  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      Tags:
        - Key: Name
          Value: Private Route Table
      VpcId: 
        Fn::ImportValue: !Sub ${ExportVpcStackName}-VPC

  PrivateRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId:
        Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateSubnet
